
all:
	Please specify spike.

log_with_function:
	gcc -Wall -Wpedantic -std=c99 -g log_with_function.c -o log_with_function

log_with_macro:
	gcc -Wall -Wpedantic -std=c99 -g log_with_macro.c -o log_with_macro

