
all:
	Please specify spike.

arg_parse:
	gcc -Wall -Wpedantic -std=c99 -g arg_parse.c ../../src/argparse.c ../../src/helper.c -o arg_parse

simple_parse:
	gcc -Wall -Wpedantic -std=c99 -g simple_parse.c -o simple_parse

std_in:
	gcc -Wall -Wpedantic -std=c99 -g std_in.c -o std_in
