
all:
	Please specify spike.

arg_parse:
	gcc -Wall -Wpedantic -std=c99 arg_parse.c ../../src/argparse.c ../../src/helper.c -g -o arg_parse

simple_parse:
	gcc -Wall -Wpedantic -std=c99 simple_parse.c -g -o simple_parse
